### ISSUE TITLE
Error deploy stack with external network

### ISSUE THREAD

**Issue by alex-labuta** [gesellix/docker-client#267]
Exception when trying to deploy stack from exists compose file (correctly started from console command _docker stack deploy_)
from groovy with command:

`def deployConfig = new DeployConfigReader(dockerClient).loadCompose(stackName, new FileInputStream(composerPath), workingDir,System.getenv());`

Output messages:

[main] INFO de.gesellix.docker.client.DockerClientImpl - using docker at 'unix:///var/run/docker.sock'
[main] INFO de.gesellix.docker.compose.ComposeFileReader - composeContent: {version=3.9, services={xmdb={image=xmdb, environment={POSTGRES_USER=postgres, POSTGRES_PASSWORD=secret, PGDATA=/var/lib/postgresql/data/pgdata}, ports=[6012:5432], networks=[xmnet-zh], volumes=[/opt/containers/xm/zh:/var/lib/postgresql/data], deploy={replicas=1}}, xmapp={depends_on=[xmdb], image=xmapp, ports=[9012:8080], networks=[xmnet-zh, ingress-routing], deploy={replicas=1, labels={ingress.host=zh.xm.local, ingress.port=8080}}}}, networks={xmnet-zh=null, ingress-routing={external=true}}}}
[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - composeContent: ComposeConfig(version=3.9, services={xmapp=StackService(build=null, capAdd=null, capDrop=null, cgroupParent=null, command=null, configs=null, containerName=null, dependsOn=[xmdb], deploy=Deploy(mode=null, replicas=1, labels=Labels(entries={ingress.host=zh.xm.local, ingress.port=8080}), updateConfig=null, resources=null, restartPolicy=null, placement=null, endpointMode=null, maxReplicasPerNode=null), devices=null, dns=null, dnsSearch=null, domainname=null, entrypoint=Entrypoint(parts=[]), envFile=null, environment=Environment(entries={}), expose=null, externalLinks=null, extraHosts=null, healthcheck=null, hostname=null, image=xmapp, ipc=null, labels=null, links=null, logging=null, macAddress=null, networkMode=null, networks={xmnet-zh=null, ingress-routing=null}, pid=null, ports=PortConfigs(portConfigs=[PortConfig(mode=ingress, target=8080, published=9012, protocol=tcp)]), privileged=null, readOnly=null, restart=null, securityOpt=null, shmSize=null, secrets=null, sysctls=null, stdinOpen=null, stopGracePeriod=null, stopSignal=null, tmpfs=null, tty=null, ulimits=null, user=null, usernsMode=null, volumes=null, workingDir=null), xmdb=StackService(build=null, capAdd=null, capDrop=null, cgroupParent=null, command=null, configs=null, containerName=null, dependsOn=null, deploy=Deploy(mode=null, replicas=1, labels=null, updateConfig=null, resources=null, restartPolicy=null, placement=null, endpointMode=null, maxReplicasPerNode=null), devices=null, dns=null, dnsSearch=null, domainname=null, entrypoint=Entrypoint(parts=[]), envFile=null, environment=Environment(entries={POSTGRES_USER=postgres, POSTGRES_PASSWORD=GhbdtnVbh, PGDATA=/var/lib/postgresql/data/pgdata}), expose=null, externalLinks=null, extraHosts=null, healthcheck=null, hostname=null, image=xmdb, ipc=null, labels=null, links=null, logging=null, macAddress=null, networkMode=null, networks={xmnet-zh=null}, pid=null, ports=PortConfigs(portConfigs=[PortConfig(mode=ingress, target=5432, published=6012, protocol=tcp)]), privileged=null, readOnly=null, restart=null, securityOpt=null, shmSize=null, secrets=null, sysctls=null, stdinOpen=null, stopGracePeriod=null, stopSignal=null, tmpfs=null, tty=null, ulimits=null, user=null, usernsMode=null, volumes=[ServiceVolume(type=bind, source=/opt/containers/xm/zh, target=/var/lib/postgresql/data, readOnly=false, consistency=, bind=null, volume=null)], workingDir=null)}, networks={xmnet-zh=null, ingress-routing=StackNetwork(driver=null, driverOpts=DriverOpts(options={}), ipam=null, external=External(external=true, name=), internal=null, attachable=false, labels=null)}, volumes=null, secrets=null, configs=null)}
[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - service network names: [xmnet-zh, ingress-routing]
[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - network configs: [xmnet-zh:NetworkCreateRequest(name=xmnet-zh, checkDuplicate=true, driver=overlay, internal=null, attachable=null, ingress=null, IPAM=null, enableIPv6=null, options=null, labels={com.docker.stack.namespace=zh})]
[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - external networks: [ingress-routing]
[main] INFO de.gesellix.docker.client.system.ManageSystemClient - docker version
[main] INFO de.gesellix.docker.client.system.ManageSystemClient - docker version
Caught: java.lang.AbstractMethodError: de.gesellix.docker.client.stack.DeployConfigReader.getProperty(Ljava/lang/String;)Ljava/lang/Object;
**java.lang.AbstractMethodError: de.gesellix.docker.client.stack.DeployConfigReader.getProperty(Ljava/lang/String;)Ljava/lang/Object;**
        at de.gesellix.docker.client.stack.DeployConfigReader$_validateExternalNetworks_closure20.doCall(DeployConfigReader.groovy:824)
        at de.gesellix.docker.client.stack.DeployConfigReader.validateExternalNetworks(DeployConfigReader.groovy:817)
        at de.gesellix.docker.client.stack.DeployConfigReader$validateExternalNetworks$1.callCurrent(Unknown Source)
        at de.gesellix.docker.client.stack.DeployConfigReader.networks(DeployConfigReader.groovy:773)
        at de.gesellix.docker.client.stack.DeployConfigReader$networks$0.callCurrent(Unknown Source)
        at de.gesellix.docker.client.stack.DeployConfigReader.loadCompose(DeployConfigReader.groovy:107)
        at de.gesellix.docker.client.stack.DeployConfigReader$loadCompose.call(Unknown Source)

Groovy 2.5.16 
JDK8

Libraries file list:
docker-client-2022-02-01T12-00-00.jar
docker-filesocket-2022-02-22T19-32-00.jar
junixsocket-common-2.4.0.jar
kotlin-logging-jvm-2.1.21.jar
kotlin-stdlib-common-1.6.10.jar
moshi-kotlin-1.12.0.jar
okio-jvm-3.0.0.jar
slf4j-api-1.7.32.jar
docker-compose-2022-02-23T22-16-00.jar
docker-remote-api-client-2022-02-23T13-45-00.jar
junixsocket-native-common-2.4.0.jar
kotlin-reflect-1.6.10.jar
kotlin-stdlib-jdk8-1.6.10.jar
okhttp-4.9.3.jar
postgresql-42.2.18.jar
slf4j-simple-1.7.32.jar
docker-engine-2022-02-22T23-12-00.jar
docker-remote-api-model-1-41-2022-02-23T11-47-00.jar
kotlin-logging-2.1.21.jar
kotlin-stdlib-1.6.10.jar
moshi-1.12.0.jar
okio-3.0.0.jar
re2j-1.6.jar
snakeyaml-1.30.jar

Also docker-client cant parse external network alias like:

```
networks:
   proxy:
      external: true
      name: ingress-routing
```

only direct naming as:

```
networks:
   ingress-routing:
      external: true
```

**Comment by alex-labuta** [comment]
@gesellix, yes, you understood correctly about issues, just to clarify, not reading but deployment.

First, i tried with a groovy-3.0.10, and stack start correctly, so error is version related. (After update prod i couil

**For groovy-2.5.16 got the following output with debug:**

[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - service network names: [xmnet-zh, ingress-routing]
[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - network configs: [xmnet-zh:NetworkCreateRequest(name=xmnet-zh, checkDuplicate=true, driver=overlay, internal=null, attachable=null, ingress=null, IPAM=null, enableIPv6=null, options=null, labels={com.docker.stack.namespace=zh})]
[main] INFO de.gesellix.docker.client.stack.DeployConfigReader - external networks: [ingress-routing]
[main] INFO de.gesellix.docker.client.system.ManageSystemClient - docker version
[main] INFO de.gesellix.docker.client.system.ManageSystemClient - docker version
Caught: java.lang.AbstractMethodError: de.gesellix.docker.client.stack.DeployConfigReader.getProperty(Ljava/lang/String;)Ljava/lang/Object;
java.lang.AbstractMethodError: de.gesellix.docker.client.stack.DeployConfigReader.getProperty(Ljava/lang/String;)Ljava/lang/Object;
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:313)
        at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:307)
        at groovy.lang.Closure.getProperty(Closure.java:296)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
        at de.gesellix.docker.client.stack.DeployConfigReader$_validateExternalNetworks_closure20.doCall(DeployConfigReader.groovy:824)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2331)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2316)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
        at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at de.gesellix.docker.client.stack.DeployConfigReader.validateExternalNetworks(DeployConfigReader.groovy:817)
        at de.gesellix.docker.client.stack.DeployConfigReader$validateExternalNetworks$1.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at de.gesellix.docker.client.stack.DeployConfigReader.networks(DeployConfigReader.groovy:773)
        at de.gesellix.docker.client.stack.DeployConfigReader$networks$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
        at de.gesellix.docker.client.stack.DeployConfigReader.loadCompose(DeployConfigReader.groovy:107)
        at de.gesellix.docker.client.stack.DeployConfigReader$loadCompose.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:151)
        at CreateNewXmDocker.dockerStackDeploy(CreateNewXmDocker.groovy:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192)
        at CreateNewXmDocker.execute(CreateNewXmDocker.groovy:57)
        at CreateNewXmDocker$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143)
        at Runner.main(Runner.groovy:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1470)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:985)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:275)
        at groovy.lang.GroovyShell.run(GroovyShell.java:376)
        at groovy.lang.GroovyShell.run(GroovyShell.java:365)
        at groovy.ui.GroovyMain.processOnce(GroovyMain.java:592)
        at groovy.ui.GroovyMain.run(GroovyMain.java:336)
        at groovy.ui.GroovyMain.access$1400(GroovyMain.java:69)
        at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:295)
        at groovy.ui.GroovyMain.processArgs(GroovyMain.java:134)
        at groovy.ui.GroovyMain.main(GroovyMain.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:110)
        at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)

-----------------------------------------------------------------------------------
**But the alias keeps failing(it no so critical), below stacktrace for alias issue:**

[main] INFO de.gesellix.docker.client.network.ManageNetworkClient - docker network inspect
[main] ERROR de.gesellix.docker.client.stack.DeployConfigReader - network proxy is declared as external, but could not be inspected. You need to create the network before the stack is deployed (with overlay driver)
Caught: java.lang.RuntimeException: java.lang.IllegalStateException: network proxy is declared as external, but could not be inspected.
java.lang.RuntimeException: java.lang.IllegalStateException: network proxy is declared as external, but could not be inspected.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at CreateNewXmDocker.execute(CreateNewXmDocker.groovy:69)
        at CreateNewXmDocker$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
        at Runner.main(Runner.groovy:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1529)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1003)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
        at groovy.lang.GroovyShell.run(GroovyShell.java:360)
        at groovy.lang.GroovyShell.run(GroovyShell.java:349)
        at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
        at groovy.ui.GroovyMain.run(GroovyMain.java:398)
        at groovy.ui.GroovyMain.access$1400(GroovyMain.java:68)
        at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:322)
        at groovy.ui.GroovyMain.processArgs(GroovyMain.java:142)
        at groovy.ui.GroovyMain.main(GroovyMain.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:111)
        at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:129)
Caused by: java.lang.IllegalStateException: network proxy is declared as external, but could not be inspected.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
        at de.gesellix.docker.client.stack.DeployConfigReader$_validateExternalNetworks_closure20.doCall(DeployConfigReader.groovy:828)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384)
        at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at de.gesellix.docker.client.stack.DeployConfigReader.validateExternalNetworks(DeployConfigReader.groovy:817)
        at de.gesellix.docker.client.stack.DeployConfigReader$validateExternalNetworks$1.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at de.gesellix.docker.client.stack.DeployConfigReader.networks(DeployConfigReader.groovy:773)
        at de.gesellix.docker.client.stack.DeployConfigReader$networks$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at de.gesellix.docker.client.stack.DeployConfigReader.loadCompose(DeployConfigReader.groovy:107)
        at de.gesellix.docker.client.stack.DeployConfigReader$loadCompose.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
        at CreateNewXmDocker.dockerStackDeploy(CreateNewXmDocker.groovy:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
        at CreateNewXmDocker.execute(CreateNewXmDocker.groovy:57)
        ... 28 more
Caused by: {"message":"network proxy not found"}
        at de.gesellix.docker.remote.api.client.NetworkApi.networkInspect(NetworkApi.kt:289)
        at de.gesellix.docker.remote.api.client.NetworkApi$networkInspect.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
        at de.gesellix.docker.client.network.ManageNetworkClient.inspectNetwork(ManageNetworkClient.groovy:47)
        at de.gesellix.docker.client.network.ManageNetworkClient.inspectNetwork(ManageNetworkClient.groovy)
        at de.gesellix.docker.client.network.ManageNetwork$inspectNetwork.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at de.gesellix.docker.client.DockerClientImpl.inspectNetwork(DockerClientImpl.groovy:66)
        at de.gesellix.docker.client.network.ManageNetwork$inspectNetwork.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at de.gesellix.docker.client.stack.DeployConfigReader$_validateExternalNetworks_closure20.doCall(DeployConfigReader.groovy:824)
        ... 74 more
